[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor
loglevel=info

[program:content_api]
command=python main_api.py --host 0.0.0.0 --port 10011 --agent_url http://localhost:10011/
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/logs/content_api.err.log
stdout_logfile=/app/logs/content_api.out.log
environment=PYTHONUNBUFFERED="1"

[program:wenshu_api]
command=python wenshu_api.py
directory=/app
autostart=true
autorestart=true
stderr_logfile=/app/logs/wenshu_api.err.log
stdout_logfile=/app/logs/wenshu_api.out.log
environment=PYTHONUNBUFFERED="1",WENSHU_API_PORT="8001"
